# https://docs.travis-ci.com/user/languages/java/
language: java


# Notifications https://docs.travis-ci.com/user/notifications/
notifications:
  email:
    recipients:
      - akropivko@gmail.com
    on_success: always # default: change
    on_failure: always # default: always
    
#after_success:
#  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
#  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js