# https://docs.travis-ci.com/user/languages/java/
language: java

#use simple (fast) mode to build to project 
sudo: false 

    
after_success:
  #- cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  #- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - bash <(curl -s https://codecov.io/bash)

 
# Notifications https://docs.travis-ci.com/user/notifications/
notifications:
  email:
    recipients:
      - akropivko@gmail.com
    on_success: change # default: change
    on_failure: always # default: always
